export const siteConfig = {
  name: "Jazora Holidays",
  shortName: "Jazora",
  tagline: "The Aura of Discovering The World",
  description:
    "Jazora Holidays designs and leads international trips from the UAE — small-group departures and private journeys across Georgia, Armenia, Azerbaijan, and beyond. Flights, stays, guides, and on-the-ground support included.",
  url: process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/$/, "") || "https://jazoraholidays.com",
  locale: "en_AE",
  phone: "+971588409478",
  phoneDisplay: "+971 58 840 9478",
  email: "info@jazoraholidays.com",
  whatsapp: "https://wa.me/971588409478",
  instagram: "https://www.instagram.com/jazoraholidays?stkn=ZTVqdmpkNTF2bzU4",
  keywords: [
    "Jazora Holidays",
    "Jazora",
    "international trips UAE",
    "Caucasus tours",
    "Georgia Armenia Azerbaijan travel",
    "small group tours",
    "private journeys",
    "trip operator Dubai",
    "guided tours from UAE",
    "WhatsApp trip booking",
  ],
} as const
